from __future__ import annotations
import argparse,os,traceback
from pathlib import Path
import cv2
from .common import dump,load,status,start_run_log,finish_run_log,log_model_use
from .scenes import detect_scenes
from .perception import analyze_video
from .grounding import enhance_perception
from .audio import analyze_audio
from .active_speaker import map_active_speakers
from .social_audio import build_social_intelligence,attach_visible_people
from .action_intelligence import build_action_intelligence,attach_social_reactions
from .planner import build_shot_plans
from .story_graph import build_story_graph,validate_story_graph
from .composition import build_composition_plan,composition_to_semantic
from .temporal_cadence import build_temporal_cadence
from .director_orchestrator import orchestrate_direction
from .editorial import apply_editorial_direction
from .crop import make_crop_keyframes
from .subtitles import make_ass
from .multiview_render import render_stage3
from .quality_supervisor import supervise_render
from .production import ProductionRuntime,runtime_config,write_crash_report,redact

def run(args):
    out=Path(args.output_dir);out.mkdir(parents=True,exist_ok=True);provider=os.getenv('CLIPPERX_PROVIDER');api_model=os.getenv('CLIPPERX_MODEL');api_key=os.getenv('CLIPPERX_API_KEY');base_url=os.getenv('CLIPPERX_BASE_URL');semi=os.getenv('CLIPPERX_SEMI_AUTOMATED','0').lower() in ('1','true','yes');manual_path=out/'semi-automated-response.json';start_run_log(out,{'input':Path(args.input).name,'profile':args.profile,'provider':provider or None,'model':api_model or None,'semiAutomated':semi});runtime=ProductionRuntime(args.input,out,runtime_config(args));args=runtime.apply_profile(args);status(out,f"Stage 9 · {runtime.profile['name']} hardware profile",2,runtimeProfile=runtime.profile)
    cap=cv2.VideoCapture(args.input);fps=cap.get(cv2.CAP_PROP_FPS) or 30;frames=cap.get(cv2.CAP_PROP_FRAME_COUNT);duration=frames/fps;cap.release()
    perception_files=['scenes.json','perception.json','grounding-report.json','identity-map.json'];runtime.begin('perception-grounding');resumed=runtime.restore('perception-grounding',perception_files)
    if resumed:
        scenes=load(out/'scenes.json',{}).get('scenes',[]);perception=load(out/'perception.json',{});grounding=load(out/'grounding-report.json',{});status(out,'Stage 9 · resumed verified perception checkpoint',32)
    else:
        status(out,'Scene detection',5);scenes=detect_scenes(args.input,duration);dump(out/'scenes.json',{'scenes':scenes});status(out,'YOLO + ByteTrack + face tracking',12);perception=analyze_video(args.input,out/'perception.json',out,args.model,args.analysis_fps,args.max_people);use_open_vocab=os.getenv('CLIPPERX_OPEN_VOCAB','1').lower() not in ('0','false','off','no');perception,grounding=enhance_perception(args.input,perception,out/'perception.json',out,lambda stage,progress:status(out,stage,progress),use_open_vocab);runtime.mark('perception-grounding',perception_files)
    runtime.end('perception-grounding',resumed)
    audio_files=['audio.json','audio.wav','action-intelligence.json','social-intelligence.json','active-speakers.json'];runtime.begin('audio-social-action');resumed=runtime.restore('audio-social-action',audio_files)
    if resumed:
        audio=load(out/'audio.json',{});actions=load(out/'action-intelligence.json',{});social=load(out/'social-intelligence.json',{});active=load(out/'active-speakers.json',{});status(out,'Stage 9 · resumed verified audio and action checkpoint',49)
    else:
        status(out,'Whisper + VAD + diarization',35);audio=analyze_audio(args.input,out/'audio.json',out,args.whisper_model,args.language,os.getenv('HF_TOKEN'));actions=build_action_intelligence(args.input,perception,audio,out/'action-intelligence.json',lambda stage,progress:status(out,stage,progress));social=build_social_intelligence(audio,perception,out/'audio.wav',out/'social-intelligence.json',lambda stage,progress:status(out,stage,progress));status(out,'Stage 6 · connecting outcomes to reactions',47);actions=attach_social_reactions(actions,social,out/'action-intelligence.json');status(out,'Mouth-motion active speaker mapping',48);active=map_active_speakers(perception,audio,out/'active-speakers.json');status(out,'Stage 5 · attaching voices and visible people',49);social=attach_visible_people(social,active,out/'social-intelligence.json');runtime.mark('audio-social-action',audio_files)
    runtime.end('audio-social-action',resumed)
    story_files=['story-graph.json','story-evidence.json'];runtime.begin('story-intelligence');resumed=runtime.restore('story-intelligence',story_files)
    if resumed:story=load(out/'story-graph.json',{});status(out,'Stage 9 · resumed verified story checkpoint',58)
    else:
        status(out,'Stage 1 · building multimodal story evidence',50);story=build_story_graph(args.input,scenes,perception,audio,active,out,None if semi else provider,None if semi else api_model,None if semi else api_key,base_url,lambda stage,progress:status(out,stage,progress),social=social,actions=actions)
        if semi and manual_path.exists():
            raw=load(manual_path,{});evidence=load(out/'story-evidence.json',{});story=validate_story_graph(raw,evidence,perception,duration);story.setdefault('provenance',{})['manualExternalAI']=True;dump(out/'story-graph.json',story);log_model_use(out,'story_intelligence','manual-external','user-supplied',True,adapter='semi-automated-json')
        elif semi:
            evidence=load(out/'story-evidence.json',{});request={'schemaVersion':'1.0','mode':'semi-automated-story-intelligence','instructions':['Upload this entire JSON file to any text AI that accepts JSON files.','Tell it to follow the prompt field and return only one JSON object matching responseSchema.','Copy the returned JSON into ClipperX. Do not edit track IDs or timestamps.'],'prompt':'Act as the coordinate-grounded Stage 1 video story director. Use only the supplied evidence. Connect setup, action, outcome and reaction; identify primary, supporting and excluded tracks; use normalized coordinates and co-visibility; never invent IDs or timestamps; return JSON only matching responseSchema.','responseSchema':{'globalSummary':'string','entities':[{'trackId':'existing id','type':'person|object','storyRole':'string','importance':0.0}],'events':[{'id':'e0','start':0.0,'end':1.0,'type':'dialogue|object_action|sports_action|outcome|reaction|group_reaction|context','narrativeRole':'setup|trigger|action|outcome|reaction|payoff|context','summary':'string','actors':[],'reactors':[],'objects':[],'targets':[],'mustShowTrackIds':[],'optionalTrackIds':[],'importance':0.0,'confidence':0.0,'keepContinuousAction':False}],'relations':[{'from':'e0','to':'e1','type':'causes|reacts_to|continues|simultaneous_with','confidence':0.0}],'directingHints':[{'eventId':'e0','primaryTrackIds':[],'supportingTrackIds':[],'excludeTrackIds':[],'spatialIntent':'single_subject|shared_region|two_independent_regions|continuous_action','coordinateReason':'numeric evidence'}],'uncertainties':[]},'evidence':evidence};dump(out/'semi-automated-request.json',request);pause={'status':'AwaitingExternalAI','progress':58,'stage':'Waiting for pasted external AI JSON','outputs':{'semiAutomatedRequest':'semi-automated-request.json'}};dump(out/'manifest.json',pause);status(out,pause['stage'],58,manifest=pause);finish_run_log(out,True,finalStage='AwaitingExternalAI',manifest='manifest.json');return pause
        else:log_model_use(out,'story_intelligence',provider,api_model,(out/'story-pass-2.json').exists(),fallback='local evidence graph' if not (out/'story-pass-2.json').exists() else None)
        status(out,'Stage 1 complete · causal story graph verified',58);runtime.mark('story-intelligence',story_files)
    runtime.end('story-intelligence',resumed)
    direction_files=['composition-plan.json','temporal-cadence.json','world-model.json','directing-decisions.json','adaptive-calibration.json','candidate-utility.json','sequence-optimization.json','predictive-risk-report.json','counterfactual-tests.json','orchestrator-report.json','executive-decision-ledger.json','editorial-plan.json','shots.json','crop-keyframes.json','subtitles.ass'];runtime.begin('composition-editorial');resumed=runtime.restore('composition-editorial',direction_files)
    if resumed:
        composition=load(out/'composition-plan.json',{});editorial=load(out/'editorial-plan.json',{});plans=load(out/'shots.json',{});crops=load(out/'crop-keyframes.json',{});status(out,'Stage 9 · resumed verified composition checkpoint',71)
    else:
        composition=build_composition_plan(story,perception,out/'composition-plan.json',provider,api_model,api_key,base_url,lambda stage,progress:status(out,stage,progress));log_model_use(out,'composition_director',provider,api_model,composition.get('apiDirector',{}).get('used',False),error=composition.get('apiDirector',{}).get('error'));status(out,'Stage 2 complete · candidate space verified',63);composition,world_model,adaptive_calibration,candidate_utility,predictive_risk,counterfactuals,orchestration=orchestrate_direction(composition,perception,active,social,actions,story,out,provider,api_model,api_key,base_url,lambda stage,progress:status(out,stage,progress));
        # Predictive risk is a repair and review signal, not a process crash. The
        # encoded-pixel quality supervisor is the final approval authority.
        composition.setdefault('stage3Contract',{})['predictiveReviewRequired']=bool(predictive_risk.get('summary',{}).get('releaseBlocked'));
        composition=build_temporal_cadence(composition,scenes,perception,active,duration,out/'temporal-cadence.json',lambda stage,progress:status(out,stage,progress));composition,editorial=apply_editorial_direction(composition,story,social,actions,args.profile,out/'editorial-plan.json',lambda stage,progress:status(out,stage,progress));semantic=load(args.semantic,{}) if args.semantic else composition_to_semantic(composition,scenes);status(out,'Stage 3 · compiling editorial viewport paths',70);plans=build_shot_plans(scenes,perception,audio,active,out/'shots.json',args.profile,semantic);crops=make_crop_keyframes(perception,plans,out/'crop-keyframes.json',args.corrections);composition.setdefault('stage3Contract',{})['rendererImplemented']=True;composition['stage3Contract']['qualityEvaluation']=True;composition['stage3Contract']['automaticCorrectionPasses']=2;composition['stage3Contract']['closedLoopSafetyFallback']=True;composition['stage3Contract']['predictiveScenarioGuard']=True;composition['stage3Contract']['adaptiveUtilityDirector']=True;composition['stage3Contract']['globalSequenceOptimization']=True;composition['stage3Contract']['nonLinearExecutiveDirector']=True;dump(out/'composition-plan.json',composition);status(out,'Stage 7 · profile-aware subtitle styling',71);make_ass(audio['words'],out/'subtitles.ass',args.width,args.height,style=editorial.get('style',{}).get('subtitleStyle',{}));runtime.mark('composition-editorial',direction_files)
    runtime.end('composition-editorial',resumed)
    render_files=['output.mp4','render-result.json','render-telemetry.json','render-evaluation.json','quality-supervisor.json','benchmark-report.json'];runtime.begin('render-quality');resumed=runtime.restore('render-quality',render_files)
    if resumed:
        result=load(out/'render-result.json',{});status(out,'Stage 9 · resumed verified final render checkpoint',100)
    else:
        ass=out/'subtitles.ass';manual_corrections=load(args.corrections,[]) if args.corrections else [];result=render_stage3(args.input,composition,perception,str(out/'output.mp4'),out,str(ass) if not args.no_subtitles else None,args.width,args.height,manual_corrections,lambda stage,progress:status(out,stage,progress));quality_provider=None if runtime.privacyMode=='strict' else provider;supervised=supervise_render(args.input,str(out/'output.mp4'),composition,perception,actions,str(ass) if not args.no_subtitles else None,out,args.width,args.height,quality_provider,api_model,api_key,lambda stage,progress:status(out,stage,progress));log_model_use(out,'quality_critic',quality_provider,api_model,supervised.get('qualitySupervisor',{}).get('aiCritique',{}).get('used',False));composition=supervised['composition'];dump(out/'composition-plan.json',composition);result['qualitySupervisor']=supervised['qualitySupervisor'];result['benchmark']=supervised['benchmark'];dump(out/'render-result.json',result);runtime.mark('render-quality',render_files)
    runtime.end('render-quality',resumed);performance=runtime.finalize(True)
    outputs={'video':'output.mp4','renderEvaluation':'render-evaluation.json','renderTelemetry':'render-telemetry.json','worldModel':'world-model.json','directingDecisions':'directing-decisions.json','temporalCadence':'temporal-cadence.json','orchestratorReport':'orchestrator-report.json','executiveDecisionLedger':'executive-decision-ledger.json','runLogs':'logs','adaptiveCalibration':'adaptive-calibration.json','candidateUtility':'candidate-utility.json','sequenceOptimization':'sequence-optimization.json','predictiveRisk':'predictive-risk-report.json','counterfactualTests':'counterfactual-tests.json','groundingReport':'grounding-report.json','identityMap':'identity-map.json','socialIntelligence':'social-intelligence.json','actionIntelligence':'action-intelligence.json','editorialPlan':'editorial-plan.json','qualitySupervisor':'quality-supervisor.json','benchmarkReport':'benchmark-report.json','compositionPlan':'composition-plan.json','storyGraph':'story-graph.json','storyEvidence':'story-evidence.json','storyCoordinateDossier':'story-coordinate-dossier.json','storyModelRouting':'story-model-routing.json','perception':'perception.json','audio':'audio.json','shots':'shots.json','crops':'crop-keyframes.json','subtitles':'subtitles.ass','performanceReport':'performance-report.json','runtimeCheckpoints':'runtime-checkpoints.json'}
    if (out/'quality-contact-sheet.jpg').exists():outputs['qualityContactSheet']='quality-contact-sheet.jpg'
    executive=load(out/'orchestrator-report.json',{}) or {};manifest={'status':'Ready','progress':100,'outputs':outputs,'render':result,'runtime':performance,'executive':{'version':'4.8.0','routeHistory':executive.get('routeHistory',[]),'decisionSummary':executive.get('decisionSummary',{}),'bestPlanScore':executive.get('planMemory',{}).get('bestScore'),'finalIssues':executive.get('finalIssues',[]),'model':executive.get('model',{})}};dump(out/'manifest.json',manifest);status(out,'Ready · production checks complete',100,manifest=manifest);finish_run_log(out,True,finalStage='Ready',manifest='manifest.json',bestPlanScore=manifest['executive']['bestPlanScore']);return manifest

def parser():
    p=argparse.ArgumentParser(description='ClipperX production video intelligence and reframing pipeline');p.add_argument('--input',required=True);p.add_argument('--output-dir',required=True);p.add_argument('--profile',default='Podcast');p.add_argument('--model',default='yolo11n.pt');p.add_argument('--whisper-model',default='base');p.add_argument('--language');p.add_argument('--analysis-fps',type=float,default=8);p.add_argument('--max-people',type=int,default=8);p.add_argument('--width',type=int,default=1080);p.add_argument('--height',type=int,default=1920);p.add_argument('--semantic');p.add_argument('--corrections');p.add_argument('--no-subtitles',action='store_true');return p

if __name__=='__main__':
    args=parser().parse_args()
    try:run(args)
    except Exception as exc:
        previous=load(Path(args.output_dir)/'status.json',{}) or {};last_stage=previous.get('stage','production processing');last_progress=int(previous.get('progress',0) or 0);crash=write_crash_report(args.output_dir,exc,traceback.format_exc());status(args.output_dir,f'Failed during {last_stage}',last_progress,error=redact(exc),crashReport='crash-report.json');finish_run_log(args.output_dir,False,finalStage=last_stage,error=redact(exc),crashReport='crash-report.json');raise
