import tempfile,unittest
from pathlib import Path
import cv2,numpy as np
from engine.dynamic_director import apply_dynamic_direction,safety_fallback_plan,apply_safety_fallback,safety_risk_score
from engine.multiview_render import _general_frame,render_silent

class DynamicDirectorTests(unittest.TestCase):
    def composition(self,confidence=.9,tracks=None):
        tracks=['1'] if tracks is None else tracks;return {'segments':[{'id':'s1','start':0,'end':2,'confidence':confidence,'mustShowTrackIds':tracks,'layout':{'layoutType':'single_focus','cells':[{'id':'c1','outputRect':[0,0,1,1],'trackIds':tracks,'sourcePolicy':'subject_lock'}]}}]}
    def perception(self,tracks=('1',),confidence=.95):
        return {'frames':[{'time':t,'detections':[{'trackId':track,'class':'person','confidence':confidence,'box':[.2+.3*i,.15,.4+.3*i,.9]} for i,track in enumerate(tracks)]} for t in (0,.5,1,1.5)]}
    def run_director(self,composition,perception,active=None,social=None,actions=None):
        with tempfile.TemporaryDirectory() as folder:return apply_dynamic_direction(composition,perception,active or {'frames':[]},social or {'reactions':[]},actions or {'episodes':[]},Path(folder)/'world.json',Path(folder)/'decisions.json')
    def test_low_confidence_uses_complete_source_instead_of_guessing(self):
        directed,world,decisions=self.run_director(self.composition(.25),{'frames':[]})
        self.assertEqual(directed['segments'][0]['layout']['layoutType'],'general_safe');self.assertEqual(decisions['summary']['safeFallbacks'],1);self.assertEqual(world['situations'][0]['confidenceLevel'],'low')
    def test_high_confidence_action_preserves_one_continuous_camera(self):
        episode={'id':'a1','start':0,'end':2,'actorTrackIds':['1'],'objectTrackIds':['2'],'targetTrackIds':['3'],'outcome':{'confidence':.96},'verification':{'verified':True}}
        directed,world,_=self.run_director(self.composition(.95,['1','2','3']),self.perception(('1','2','3')),
            actions={'episodes':[episode]})
        segment=directed['segments'][0];self.assertTrue(segment['keepContinuousAction']);self.assertEqual(segment['dynamicDirector']['policy'],'action_camera');importance={row['trackId']:row['score'] for row in world['situations'][0]['importance']};self.assertGreater(importance['2'],importance['1'])
    def test_optional_bystander_does_not_gain_narrative_importance(self):
        _,world,_=self.run_director(self.composition(.95,['1']),self.perception(('1','99')),active={'frames':[{'time':.5,'personTrackId':'1','confidence':.95}]})
        important={row['trackId'] for row in world['situations'][0]['importance']};self.assertIn('1',important);self.assertNotIn('99',important)
    def test_uncertain_split_is_vetoed(self):
        composition=self.composition(.65,['1','2']);composition['segments'][0]['layout']={'layoutType':'split_2_stack','cells':[{'id':'a','outputRect':[0,0,1,.5],'trackIds':['1']},{'id':'b','outputRect':[0,.5,1,.5],'trackIds':['2']}]}
        directed,_,_=self.run_director(composition,self.perception(('1','2'),.65));self.assertEqual(directed['segments'][0]['layout']['layoutType'],'stable_wide')
    def test_action_evidence_repairs_incomplete_story_plan(self):
        episode={'id':'a1','start':0,'end':2,'actorTrackIds':['1'],'objectTrackIds':['2'],'targetTrackIds':['3'],'phases':{'action':[0,2]},'verification':{'verified':True},'outcome':{'confidence':.9}}
        directed,world,_=self.run_director(self.composition(.95,['1']),self.perception(('1','2','3')),actions={'episodes':[episode]});self.assertEqual(set(directed['segments'][0]['mustShowTrackIds']),{'1','2','3'});self.assertEqual(directed['segments'][0]['layout']['layoutType'],'stable_wide');self.assertEqual(set(world['situations'][0]['independentlyAddedTrackIds']),{'2','3'})
    def test_outcome_phase_drops_unnecessary_actor_but_keeps_object_and_target(self):
        composition=self.composition(.95,[]);composition['segments'][0]['layout']['cells'][0]['trackIds']=[];episode={'id':'a1','start':0,'end':2,'actorTrackIds':['actor'],'objectTrackIds':['ball'],'targetTrackIds':['goal'],'phases':{'outcome':[0,2]},'verification':{'verified':True},'outcome':{'confidence':.95}}
        directed,world,_=self.run_director(composition,self.perception(('actor','ball','goal')),actions={'episodes':[episode]});required=set(world['situations'][0]['requiredTrackIds']);self.assertEqual(required,{'ball','goal'});self.assertNotIn('actor',directed['segments'][0]['mustShowTrackIds'])
    def test_short_object_occlusion_uses_memory_instead_of_abandoning_action(self):
        composition={'segments':[{'id':'s1','start':1,'end':1.5,'confidence':.95,'mustShowTrackIds':['ball'],'layout':{'layoutType':'single_focus','cells':[{'id':'c','outputRect':[0,0,1,1],'trackIds':['ball'],'sourcePolicy':'trajectory_follow'}]}}]};perception={'frames':[{'time':.8,'detections':[{'trackId':'ball','class':'sports ball','confidence':.95,'box':[.4,.4,.5,.5],'velocity':[.1,0]}]},{'time':1.8,'detections':[]}]};directed,world,_=self.run_director(composition,perception,actions={'episodes':[{'id':'a','start':.5,'end':2,'objectTrackIds':['ball'],'verification':{'verified':True},'outcome':{'confidence':.8}}]});item=world['situations'][0]['importance'][0];self.assertTrue(item['predicted']);self.assertNotIn('ball',world['situations'][0]['missingTrackIds']);self.assertNotEqual(directed['segments'][0]['dynamicDirector']['policy'],'general_safe')
    def test_safety_risk_uses_failure_magnitude_not_only_failure_count(self):
        slight={'metrics':{'requiredCoverageRate':.93,'actionPhaseCoverage':1,'faceClippingRate':0,'bodyClippingRate':0,'blankCellRate':0,'jitterScore':0,'blackFrameRate':0}};severe={'metrics':{**slight['metrics'],'requiredCoverageRate':.2}};self.assertGreater(safety_risk_score(severe),safety_risk_score(slight)*10)
    def test_single_juggler_never_uses_full_source_when_performer_is_tracked(self):
        composition=self.composition(.3,['person','ball']);perception={'frames':[{'time':t,'detections':[{'trackId':'person','class':'person','confidence':.9,'box':[.35,.1,.65,.95]},{'trackId':'ball','class':'sports ball','confidence':.72,'box':[.48,.25+.15*(t%1),.55,.32+.15*(t%1)],'velocity':[0,.2]}]} for t in (0,.5,1,1.5)]};episode={'id':'juggle','start':0,'end':2,'actorTrackIds':['person'],'objectTrackIds':['ball'],'phases':{'action':[0,2]},'verification':{'verified':True},'outcome':{'confidence':.55}};directed,_,_=self.run_director(composition,perception,actions={'episodes':[episode]});self.assertEqual(directed['segments'][0]['dynamicDirector']['policy'],'action_camera');self.assertNotEqual(directed['segments'][0]['layout']['layoutType'],'general_safe')
    def test_juggling_evidence_removes_silent_bystander_from_crop(self):
        composition=self.composition(.9,['juggler','ball','silent']);perception={'frames':[{'time':t,'detections':[{'trackId':'juggler','class':'person','confidence':.95,'box':[.08,.08,.34,.95]},{'trackId':'ball','class':'sports ball','confidence':.9,'box':[.2,.2,.25,.25],'velocity':[0,.16]},{'trackId':'silent','class':'person','confidence':.98,'box':[.7,.08,.96,.95]}]} for t in (0,.5,1,1.5)]};episode={'id':'juggle','start':0,'end':2,'actorTrackIds':['juggler'],'objectTrackIds':['ball'],'phases':{'action':[0,2]},'verification':{'verified':True}}
        directed,world,_=self.run_director(composition,perception,actions={'episodes':[episode]});required=set(directed['segments'][0]['mustShowTrackIds']);self.assertEqual(required,{'juggler','ball'});self.assertNotIn('silent',required);self.assertTrue(world['policy']['silentBystandersAreNotPromoted'])
    def test_ambiguous_action_actor_list_keeps_person_nearest_moving_object(self):
        composition=self.composition(.9,['juggler','silent','ball']);perception={'frames':[{'time':t,'detections':[{'trackId':'juggler','class':'person','confidence':.95,'box':[.1,.08,.34,.95]},{'trackId':'silent','class':'person','confidence':.98,'box':[.7,.08,.96,.95]},{'trackId':'ball','class':'sports ball','confidence':.9,'box':[.2,.2,.25,.25],'velocity':[0,.16]}]} for t in (0,.5,1,1.5)]};episode={'id':'juggle','start':0,'end':2,'actorTrackIds':['juggler','silent'],'objectTrackIds':['ball'],'phases':{'action':[0,2]},'verification':{'verified':True}}
        directed,_,_=self.run_director(composition,perception,actions={'episodes':[episode]});self.assertEqual(set(directed['segments'][0]['mustShowTrackIds']),{'juggler','ball'})
    def test_hurried_speaker_and_close_reactors_use_two_views_not_grid(self):
        composition=self.composition(.9,['speaker','r1','r2']);composition['segments'][0]['end']=1;composition['segments'][0]['layout']={'layoutType':'grid_4','cells':[{'id':'a','outputRect':[0,0,.5,.5],'trackIds':['speaker']},{'id':'b','outputRect':[.5,0,.5,.5],'trackIds':['r1']},{'id':'c','outputRect':[0,.5,.5,.5],'trackIds':['r2']}]};tracks={'speaker':[.06,.08,.3,.95],'r1':[.66,.08,.78,.95],'r2':[.8,.08,.92,.95]};perception={'frames':[{'time':t,'detections':[{'trackId':track,'class':'person','confidence':.95,'box':box} for track,box in tracks.items()]} for t in (0,.25,.5,.75)]};active={'frames':[{'time':t,'personTrackId':'speaker','confidence':.96} for t in (0,.25,.5,.75)],'segments':[{'start':0,'end':1,'personTrackId':'speaker'}]};social={'reactions':[{'id':'laugh','start':.1,'end':.9,'participants':['r1','r2'],'confidence':.92}]}
        directed,world,_=self.run_director(composition,perception,active=active,social=social);layout=directed['segments'][0]['layout'];self.assertEqual(layout['layoutType'],'speaker_reaction_split');self.assertEqual(len(layout['cells']),2);self.assertEqual(layout['cells'][0]['trackIds'],['speaker']);self.assertEqual(set(layout['cells'][1]['trackIds']),{'r1','r2'});self.assertTrue(world['situations'][0]['hurriedBeat'])
    def test_one_reliable_person_gets_stable_crop_at_low_semantic_confidence(self):
        directed,_,_=self.run_director(self.composition(.32,['1']),self.perception(('1',),.86));self.assertEqual(directed['segments'][0]['layout']['layoutType'],'stable_subject')
    def test_rapid_balanced_two_group_dialogue_uses_persistent_borderless_split(self):
        tracks={'l1':[.08,.1,.18,.9],'l2':[.22,.1,.32,.9],'r1':[.68,.1,.78,.9],'r2':[.82,.1,.92,.9]};perception={'frames':[{'time':t,'detections':[{'trackId':track,'class':'person','confidence':.94,'box':box} for track,box in tracks.items()]} for t in (0,.5,1,1.5)]};active={'frames':[{'time':0,'personTrackId':'l1','confidence':.9},{'time':.5,'personTrackId':'r1','confidence':.9},{'time':1,'personTrackId':'l2','confidence':.9},{'time':1.5,'personTrackId':'r2','confidence':.9}],'segments':[{'start':0,'end':.5,'personTrackId':'l1'},{'start':.5,'end':1,'personTrackId':'r1'},{'start':1,'end':1.5,'personTrackId':'l2'},{'start':1.5,'end':2,'personTrackId':'r2'}]};directed,world,_=self.run_director(self.composition(.9,['l1']),perception,active=active);layout=directed['segments'][0]['layout'];self.assertEqual(layout['layoutType'],'conversation_split');self.assertEqual(len(layout['cells']),2);self.assertEqual(layout['hardConstraints']['cellGap'],0);self.assertTrue(world['situations'][0]['balancedClusters'])
    def test_dominance_uses_speech_story_not_largest_body_box(self):
        perception={'frames':[{'time':t,'detections':[{'trackId':'left','class':'person','confidence':.95,'box':[.12,.25,.24,.65]},{'trackId':'left2','class':'person','confidence':.9,'box':[.26,.2,.38,.7]},{'trackId':'rightHuge','class':'person','confidence':.95,'box':[.55,.02,.98,.98]}]} for t in (0,.5,1,1.5)]};active={'frames':[{'time':0,'personTrackId':'left','confidence':.95},{'time':.5,'personTrackId':'left','confidence':.95},{'time':1,'personTrackId':'left','confidence':.95},{'time':1.5,'personTrackId':'rightHuge','confidence':.5}],'segments':[{'start':0,'end':1.5,'personTrackId':'left'},{'start':1.5,'end':1.8,'personTrackId':'rightHuge'}]};directed,world,_=self.run_director(self.composition(.9,['left']),perception,active=active);preferred=set(world['situations'][0]['preferredTrackIds']);self.assertEqual(preferred,{'left'});self.assertNotIn('rightHuge',preferred);self.assertEqual(directed['segments'][0]['layout']['layoutType'],'group_hold')
    def test_short_opposite_group_turn_does_not_force_hurried_camera_jump(self):
        segments=[{'id':'a','start':0,'end':1.5,'confidence':.9,'mustShowTrackIds':['left'],'layout':{'layoutType':'single_focus','cells':[{'id':'x','outputRect':[0,0,1,1],'trackIds':['left']}]}},{'id':'b','start':1.5,'end':2,'confidence':.9,'mustShowTrackIds':['right'],'layout':{'layoutType':'single_focus','cells':[{'id':'y','outputRect':[0,0,1,1],'trackIds':['right']}]}}];perception={'frames':[{'time':t,'detections':[{'trackId':'left','class':'person','confidence':.95,'box':[.1,.1,.3,.9]},{'trackId':'left2','class':'person','confidence':.9,'box':[.31,.1,.43,.9]},{'trackId':'right','class':'person','confidence':.95,'box':[.7,.1,.9,.9]}]} for t in (0,.5,1,1.5)]};active={'frames':[{'time':0,'personTrackId':'left','confidence':.95},{'time':.5,'personTrackId':'left','confidence':.95},{'time':1,'personTrackId':'left','confidence':.95},{'time':1.5,'personTrackId':'right','confidence':.8}],'segments':[{'start':0,'end':1.5,'personTrackId':'left'},{'start':1.5,'end':2,'personTrackId':'right'}]};directed,_,_=self.run_director({'segments':segments},perception,active=active);first=set(directed['segments'][0]['layout']['cells'][0]['trackIds']);second=set(directed['segments'][1]['layout']['cells'][0]['trackIds']);self.assertEqual(first,second);self.assertIn('left',second)
    def test_full_source_post_render_fallback_requires_catastrophic_coverage_loss(self):
        composition={'segments':[{'id':'a','start':0,'end':1,'mustShowTrackIds':['1'],'layout':{}}]};report={'failures':['requiredCoverageRate'],'metrics':{'requiredCoverageRate':.55,'actionPhaseCoverage':1},'faceAndCaption':{'segments':{}}};self.assertEqual(safety_fallback_plan(report,composition)['mode'],'general_safe');report['metrics']['requiredCoverageRate']=.9;self.assertEqual(safety_fallback_plan(report,composition)['mode'],'stable_wide')
    def test_general_fallback_preserves_circle_aspect(self):
        source=np.zeros((90,160,3),dtype=np.uint8);cv2.circle(source,(80,45),25,(255,255,255),-1);output=_general_frame(source,90,160);gray=cv2.cvtColor(output,cv2.COLOR_BGR2GRAY);ys,xs=np.where(gray>240);self.assertLess(abs((xs.max()-xs.min())-(ys.max()-ys.min())),3)
    def test_failed_body_safety_targets_only_failed_segments(self):
        composition={'segments':[{'id':'a','start':0,'end':1,'mustShowTrackIds':['1'],'layout':{}},{'id':'b','start':1,'end':2,'mustShowTrackIds':['2'],'layout':{}}]};report={'failures':['bodyClippingRate'],'metrics':{'requiredCoverageRate':.95,'actionPhaseCoverage':1},'faceAndCaption':{'segments':{'a':{'bodyClipped':1},'b':{'bodyClipped':0}}}};plan=safety_fallback_plan(report,composition);patched=apply_safety_fallback(composition,plan);self.assertEqual(plan['segmentIds'],['a']);self.assertEqual(patched['segments'][0]['layout']['layoutType'],'stable_wide');self.assertNotEqual(patched['segments'][1]['layout'].get('layoutType'),'stable_wide')
    def test_general_renderer_has_zero_camera_motion(self):
        with tempfile.TemporaryDirectory() as folder:
            folder=Path(folder);source=folder/'input.mp4';writer=cv2.VideoWriter(str(source),cv2.VideoWriter_fourcc(*'mp4v'),5,(160,90))
            for index in range(6):writer.write(np.full((90,160,3),index*20,dtype=np.uint8))
            writer.release();composition=self.composition(.1);directed,_,_=self.run_director(composition,{'frames':[]});telemetry=render_silent(source,directed,{'frames':[]},folder/'out.mp4',folder,90,160)
            views=[cell['view'] for sample in telemetry['samples'] for cell in sample['cells']];self.assertTrue(all(view=={'centerX':.5,'centerY':.5,'cropWidth':1,'cropHeight':1} for view in views))
if __name__=='__main__':unittest.main()
